<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ssdRoot" nsURI="http:///ssdRoot.ecore" nsPrefix="ssdRoot">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="communication" upperBound="-1"
        eType="#//Communication" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communication" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserCommunication" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" ordered="false"
        lowerBound="1" eType="#//Return"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Return"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemCommunication" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstState" ordered="false"
        lowerBound="1" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemmessage" ordered="false"
        lowerBound="1" eType="#//SystemMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" ordered="false"
        lowerBound="1" eType="#//Return"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondState" ordered="false"
        lowerBound="1" eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false"
        lowerBound="1" eType="#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false"
        lowerBound="1" eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemobject" ordered="false"
        lowerBound="1" eType="#//SystemObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemObject" eSuperTypes="#//Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false"
        lowerBound="1" eType="#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false"
        lowerBound="1" eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" ordered="false" lowerBound="1"
        eType="#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Return">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Return"/>
</ecore:EPackage>
